Add auto-rerun failed jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -351,6 +351,26 @@ jobs:
           cd ultralytics
           git checkout tags/v$VERSION
           pytest tests
+  FailTest:
+    runs-on: ubuntu-latest
+    if: github.run_attempt == 1
+    steps:
+      - name: Simulate a failing step
+        run: |
+          echo "This job fails intentionally on the first attempt"
+          exit 1
+
+  Rerun-failed-jobs:
+    runs-on: ubuntu-latest
+    needs: [HUB, Benchmarks, Tests, GPU, RaspberryPi, Conda, FailTest]
+    if: failure() && github.run_attempt == 1
+    steps:
+      - name: Install GitHub CLI
+        run: sudo apt-get install gh -y
+      - name: Rerun failed jobs in the current workflow
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+        run: gh run rerun ${{ github.run_id }} --failed
 
   Summary:
     runs-on: ubuntu-latest
