Update links.yml with `set -o pipefail`
Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com>

diff --git a/.github/workflows/links.yml b/.github/workflows/links.yml
--- a/.github/workflows/links.yml
+++ b/.github/workflows/links.yml
@@ -35,6 +35,7 @@ jobs:
           retry_delay_seconds: 900
           retries: 2
           run: |
+            set -o pipefail  # This makes the pipeline return the exit code of the first failing command
             lychee \
             --scheme https \
             --timeout 60 \
@@ -65,6 +66,7 @@ jobs:
           retry_delay_seconds: 900
           retries: 2
           run: |
+            set -o pipefail  # This makes the pipeline return the exit code of the first failing command
             lychee \
             --scheme https \
             --timeout 60 \
